### ISSUE TITLE
Not working for me, circles are in the wrong places

### ISSUE THREAD

**Issue by trihardseven** [C1rdec/Lilith-Lurker#3]
<img width="146" alt="LilithLurker_Ker0RnOPQc" src="https://github.com/C1rdec/Lilith-Lurker/assets/54422205/b9011c5f-03b3-4ddd-848a-7e5478414259">

Maybe because I use ultrawide?

**Comment by C1rdec** [comment]
What's your resolution and your scaling?

![image](https://github.com/C1rdec/Lilith-Lurker/assets/5436436/651ef3ec-2331-4f37-8b66-8eed32e02aab)

**Comment by C1rdec** [comment]
yeah its the scaling...

On it

**Comment by C1rdec** [comment]
Fixed in 1.2.1

**Comment by C1rdec** [comment]
You'll need to delete this file:

`"C:\Users\<user>\AppData\Roaming\LilithLurker\Statues.json"`
