### ISSUE TITLE
Overlay misplaced

### ISSUE THREAD

**Issue by THenkeDE** [C1rdec/Lilith-Lurker#5]
Hey, thanks for this awesome tool but sadly i cannot use it as everything in your map overlay is misplaced
![misplaceoverlay](https://github.com/C1rdec/Lilith-Lurker/assets/7956104/938a967e-d308-4131-9edc-88f75e329925)

If there is anything i can do to help sort this out just get back to me.

**Comment by C1rdec** [comment]
Lets connect on discord you need to make sure 
- The tool is closed
- Delete the appdata folder 
- Use the latest version

**Comment by eskoONE** [comment]
> Lets connect on discord you need to make sure
> 
>     * The tool is closed
> 
>     * Delete the LilithLurker appdata folder
> 
>     * Use the latest version
> 
> 
> https://discord.gg/gaaq3n3P

I have this very same issue. The discord link has expired.
